<!-- content -->
<div class="splitleft">
<h1>Terms of Use<h1>
<h2>TERMS AND CONDITIONS</h2>
<p></p>
<p>The Terms and Conditions contained herein constitute the legal agreement that governs your use of the GrowOurYields.com website and includes any and all other services (“Service”) that may be provided by GrowOurYields, LLC (“Company” or “Grow Our Yields”).   These Terms and Conditions (“Agreement”) are by and between GrowOurYields and any user of this site (“User”) that agrees to the Terms and Conditions of the Agreement.  Please read these Terms and Conditions carefully.</p>
<p>At the end of this Agreement you agree to these and Terms and Conditions by selecting “YES”.  If you do not agree to these Terms And Conditions, click  “NO” and by doing so you will not be allowed to use the website or any other services provided by the Company.</p>
<p>If you violate or fail to comply with any of these provisions of this Agreement, the Company may terminate your access to the Site and to your GrowOurYields.com account immediately without notice to you.</p>
<h2>DATA USE AND OWNERSHIP</h2>
<p>The parties to this Agreement understand and accept the following related to the use and ownership of any data or information proprietary to the User (“Data”) that is provided to the Company by the User regardless of whether it is has been transferred in digital format, provided in text documents or any and all other formats.  The Data are any and all data and/or information specific to the User’s business.</p>
<p>It is agreed by all parties hereto that any and all individual User Data provided to the Company shall remain the sole and exclusive property of the User. </p>
<p>It is agreed that any and all User Data will be used by the Company to provide data access and information services to the User.  The Company’s purpose in doing so is to provide information back to the User that may be of value to the User in the management of their business.  It will be the Company’s responsibility to the User to respect the User’s rights of Data ownership and privacy and act in an ethical, responsible and professional manner with regard to the use of the Data.  The Company is expressly prohibited from providing or sharing individual User Data with any other third party without permission from the User; provided, however, that  employees, representatives, and contractors of the Company who have signed appropriate confidentiality and non-disclosure agreements with the Company shall have access to and be allowed to work with the User’s Data.</p>
<h2>AGGREGATE DATA</h2>
<p>Aggregate data is a collection of Data compiled from multiple Users.  The User hereby acknowledges the value of aggregating their Data with any other Data received by the Company for analysis with the intention of developing and providing management tools, information and reports of interest and value to the User.   For this purpose, the User hereby authorizes the Company to collect, organize, store, and aggregate with other Users’ Data in order to analyze, create information studies and reports,  transmit and otherwise manage Data provided by Users to the Company. </p>
<p>Data will be sufficiently aggregated to protect the identity and privacy of the User and the User hereby authorizes the Company to share the results of any such aggregate analysis with other Users and third parties.  Any such aggregate data and the results of any subsequent analysis are not owned by nor the property of the User, but rather are the sole and exclusive property of the Company.  In the event the User terminates doing business with the Company, a copy of the User Data will remain accessible via the GrowOurYields.com website.  The Company is hereby authorized to retain and continue to use a copy of the User Data for the original purposes intended herein and according to the restrictions agreed to herein.  </p>
<h2>DISCLAIMER OF LIABILITY</h2>
<p>Neither GrowOurYields nor any of its members, managers, representatives, employees or agents, shall be held liable for any improper or incorrect use of the information described and/or contained on the GrowOurYields website and assumes no responsibility for anyone's use of the information. In no event shall GrowOurYields or its members, managers, representatives, employees or agents be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement or substitute goods or services; loss of use, data, or profits; or business interruption) however caused and under any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way out of the use of this system, even if advised of the possibility of such damage. This disclaimer of liability applies to any damages or injury, including but not limited to those caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortious behavior, negligence or under any other cause of action.</p>
<h2>DISCLAIMER OF WARRANTIES AND ACCURACY OF DATA</h2>
<p>Although the data found on GrowOurYields has been produced and processed from sources believed to be reliable, no independent verification or investigation of such data has been undertaken and, accordingly, no warranty, express or implied, is made regarding accuracy, adequacy, completeness, legality, reliability or usefulness of any information. This disclaimer applies to both isolated and aggregate uses of the information. GrowOurYields provides this information solely on an "as is" basis. All warranties of any kind, express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, freedom from contamination by computer viruses and non-infringement of proprietary rights are expressly disclaimed. Changes may be periodically made to the information herein; these changes may or may not be incorporated in any new version of the website.</p>
<h2>MODIFICATION OF TERMS</h2>
<p>GrowOurYields reserves the right to modify or discontinue, temporarily or permanently, the Site for any reason, at its sole discretion, with or without notice to you. GrowOurYields may likewise change the Terms from time to time with or without notice to you. You agree to review the Terms periodically to ensure that you are aware of any modifications. Your continued access to the Site after the modifications have become effective shall be deemed your conclusive acceptance of the modified Terms. No modifications to the Terms made by you will be binding, unless expressly authorized in writing by GrowOurYields.</p>
<h2>RESOLUTION OF DISPUTES</h2>
<p>Should a dispute arise from an event or events between the User and the Company, any potential liability of the Company shall be limited to the amount of fees paid by the User to the Company during the year in which the event or events occurred.</p>
<br>
</div>

